services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/dist:/usr/share/nginx/html

  backend:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile.prod
    volumes:
      - ./backend/db:/root/db
    networks:
      - app-network

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
