services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8081:8081"
    volumes:
      - ./backend/db:/root/db

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    


