# air 設定
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "tmp/main"
delay = 1000
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
log = "stdout"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
